# Generated by Django 4.1.4 on 2022-12-28 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aluno',
            new_name='Student',
        ),
    ]
