# Generated by Django 4.1.4 on 2022-12-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='about',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='XOE967149', max_length=9),
        ),
    ]
