# Generated by Django 4.1.4 on 2022-12-30 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0002_alter_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='teacher',
        ),
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registration_course', to='schoolapi.course'),
            preserve_default=False,
        ),
    ]
