# Generated by Django 4.1.4 on 2022-12-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0002_teacher_course_totalclass_student_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='totalClass',
            new_name='workload',
        ),
    ]
