# Generated by Django 4.1.4 on 2022-12-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0002_teacher_about_alter_registration_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='code',
            field=models.CharField(default='IWF740322', max_length=9),
        ),
    ]
