# Generated by Django 4.1.4 on 2022-12-28 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0003_rename_totalclass_course_workload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='workload',
        ),
    ]
