# Generated by Django 4.1.4 on 2022-12-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0004_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.CharField(default=123123, max_length=8),
            preserve_default=False,
        ),
    ]
