# Generated by Django 4.1.4 on 2022-12-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0005_student_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
