# Generated by Django 4.1.4 on 2022-12-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0005_alter_course_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=35),
        ),
    ]
