# Generated by Django 4.1.4 on 2022-12-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0006_student_createdat_student_updatedat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
