# Generated by Django 4.1.4 on 2022-12-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapi', '0007_rename_createdat_student_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
    ]
